# Generated by Django 3.0.2 on 2020-05-10 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_delete_orders'),
        ('orders', '0002_remove_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Started', max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Configuration')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
