# Generated by Django 3.0.2 on 2020-05-11 11:37

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_auto_20200510_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userID',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expiration_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_security_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_on_card',
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default='Lithuania', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
        migrations.CreateModel(
            name='Payment_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.CharField(default='', max_length=50)),
                ('card_holder_name', models.CharField(max_length=26)),
                ('card_number', creditcards.models.CardNumberField(max_length=25, null=True)),
                ('card_expiration_date', creditcards.models.CardExpiryField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
