# Generated by Django 3.0.2 on 2020-05-11 12:05

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200511_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='card_expiration_date',
            field=creditcards.models.CardExpiryField(max_length=5, null=True),
        ),
    ]
