# Generated by Django 3.0.2 on 2020-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200511_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_info',
            name='card_expiration_date',
            field=models.CharField(default='11 22', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment_info',
            name='card_number',
            field=models.CharField(default='5555 5555 5555 5555', max_length=19),
            preserve_default=False,
        ),
    ]
