# Generated by Django 3.0.2 on 2020-05-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200511_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Being processed', 'Being processed'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled'), ('Finished', 'Finished')], default='Started', max_length=50),
        ),
    ]
