# Generated by Django 3.0.2 on 2020-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200331_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Content', models.TextField()),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
