# Generated by Django 3.0.2 on 2020-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200411_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboard',
            name='Description',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Recomendations',
            field=models.TextField(default='testing'),
            preserve_default=False,
        ),
    ]
