# Generated by Django 3.0.2 on 2020-04-25 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_configuration_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='Date_Saved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
