# Generated by Django 3.0.2 on 2020-04-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_cpu_supported_ram_speeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Supported_PSU_Form_Factor',
            field=models.CharField(default='field not filed', max_length=50),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='Generation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='Length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Supported_CPU_generations',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='Supported_ram_types',
            field=models.CharField(max_length=100),
        ),
    ]
