# Generated by Django 3.0.2 on 2020-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200429_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpu',
            name='Price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
