# Generated by Django 3.0.2 on 2020-05-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200509_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='UserID',
        ),
    ]
