# Generated by Django 3.0.2 on 2020-05-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_configuration_userid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
