# Generated by Django 3.0.2 on 2020-05-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200512_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='saved_build',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
