# Generated by Django 3.0.2 on 2020-05-13 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200512_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Aspect_Ratio', models.CharField(max_length=10)),
                ('Diameter', models.CharField(max_length=10)),
                ('Resolution', models.CharField(max_length=20)),
                ('Connections', models.CharField(max_length=100)),
                ('Display_Technology', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Image', models.ImageField(default='default.jpg', upload_to='Part_Pics/Monitors')),
                ('Description', models.TextField(default='not yet available')),
                ('Recommendations', models.TextField(default='not yet available')),
            ],
        ),
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Image', models.ImageField(default='default.jpg', upload_to='Part_Pics/Operating_Systems')),
            ],
        ),
        migrations.CreateModel(
            name='Optical_Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Read_Speed', models.TextField(max_length=300)),
                ('Write_Speed', models.TextField(max_length=300)),
                ('Access_Time', models.CharField(max_length=50)),
                ('Connection', models.CharField(max_length=20)),
                ('Mounting_Orientation', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Image', models.ImageField(default='default.jpg', upload_to='Part_Pics/Optical_Drives')),
                ('Description', models.TextField(default='not yet available')),
                ('Recommendations', models.TextField(default='not yet available')),
            ],
        ),
        migrations.CreateModel(
            name='Sound_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Connection', models.CharField(max_length=20)),
                ('Internal', models.BooleanField()),
                ('Channel', models.CharField(max_length=10)),
                ('High_Res_audio', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Image', models.ImageField(default='default.jpg', upload_to='Part_Pics/Sound_Cards')),
                ('Description', models.TextField(default='not yet available')),
                ('Recommendations', models.TextField(default='not yet available')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='Optical_Drive_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Monitor'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Operating_System',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Operating_System'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Optical_Drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Optical_Drive'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='Sound_Card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Sound_Card'),
        ),
    ]
