# Generated by Django 3.0.2 on 2020-05-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200513_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='Refresh_Rate',
            field=models.CharField(default='60 Hz', max_length=20),
            preserve_default=False,
        ),
    ]
