# Generated by Django 3.0.2 on 2020-05-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_monitor_refresh_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='operating_system',
            name='Brand',
            field=models.CharField(default='Microsoft', max_length=50),
        ),
    ]
