# Generated by Django 3.0.2 on 2020-05-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200513_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motherboard',
            old_name='Nr_of_PCIe_slots',
            new_name='Nr_of_PCIe_x16_slots',
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Nr_of_PCIe_x1_slots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motherboard',
            name='Nr_of_PCIe_x4_slots',
            field=models.IntegerField(default=0),
        ),
    ]
