# Generated by Django 3.0.2 on 2020-05-11 11:37

from django.db import migrations
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
